name: release
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup node
      uses: actions/setup-node@master
    
    - name: Build
      run: |
        npm install -g nw-builder
        nwbuild -p win32,win64,osx64,linux32,linux64 .
    
    - name: Pack
      run: |
        ls "build/CodeForces Contest Helper/win32"
        zip -r CCHv2.alpha.${{ github.run_id }}.win32.zip "build/CodeForces Contest Helper/win32/*"
        zip -r CCHv2.alpha.${{ github.run_id }}.win64.zip "build/CodeForces Contest Helper/win64/*"
        zip -r CCHv2.alpha.${{ github.run_id }}.osx64.zip "build/CodeForces Contest Helper/osx64/*"
        zip -r CCHv2.alpha.${{ github.run_id }}.linux32.zip "build/CodeForces Contest Helper/linux32/*"
        zip -r CCHv2.alpha.${{ github.run_id }}.linux64.zip "build/CodeForces Contest Helper/linux64/*"
    
    - name: Create Tag
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        tag: Alpha${{ github.run_id }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: true
        files: |
          CCHv2.alpha.${{ github.run_id }}.win32.zip
          CCHv2.alpha.${{ github.run_id }}.win64.zip
          CCHv2.alpha.${{ github.run_id }}.osx64.zip
          CCHv2.alpha.${{ github.run_id }}.linux32.zip
          CCHv2.alpha.${{ github.run_id }}.linux64.zip
        name: CCHv2 Alpha ${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   