name: Auto Release
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Pack
      uses: actions/setup-node@master
    - run: |
        npm install -g nw-builder
        nwbuild .
        ls -R build


   